openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/tutorial/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /student/{student_id}:
    get:
      summary: gets student
      description: Returns a single student
      operationId: get_student_by_id
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        "400":
          description: Invalid ID
        "404":
          description: Not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: deletes a student
      description: "delete a single student  \n"
      operationId: delete_student
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: integer
      responses:
        "200":
          description: Sucsessful deletion
        "400":
          description: Bad request
        "404":
          description: Specified student not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /student:
    post:
      summary: Add a new student
      description: Adds an item to the system
      operationId: add_student
      requestBody:
        description: Student item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        "200":
          description: created
          content:
            application/json:
              schema:
                type: string
                format: uuid
                x-content-type: application/json
        "400":
          description: "invalid input, object invalid"
        "409":
          description: Already exists
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Student:
      title: Student
      required:
      - first_name
      - last_name
      - student_id
      type: object
      properties:
        student_id:
          minimum: 0
          type: integer
          format: int32
        first_name:
          type: string
          x-stoplight:
            id: tyfx85jf86bw1
        last_name:
          type: string
          x-stoplight:
            id: jd2ggv8m6fc13
        grade_records:
          type: array
          items: {}
          x-stoplight:
            id: ncok6f6a20sdg
      example:
        student_id: 0
        last_name: last_name
        grade_records:
        - ""
        - ""
        first_name: first_name
      x-examples:
        Example 1:
          student_id: 564782
          first_name: Jane
          last_name: Smith
          grade_records:
          - null
    GradeRecord:
      title: GradeRecord
      type: object
      properties:
        subject_name:
          type: string
        grade:
          maximum: 10
          minimum: 0
          type: number
          format: float
          x-stoplight:
            id: erxt16sdfnheg
      x-examples:
        Example 1:
          subject_name: DevOps
          grade: 9.5
        Example 2:
          subject_name: string
          grade: 8

